#  Exploratory Data Analysis — Books Sales and Ratings

> **Dataset source :** Kaggle   
> **Niveau :** Académique — Projet EDA complet  

---

## Table des matières
1. [Introduction](#section0)
2. [Compréhension des données](#section1)
3. [Nettoyage des données](#section2)
4. [Feature Engineering](#section3)
5. [Visualisation & Analyse exploratoire](#section4)
6. [Hypothèses & Conclusions](#section5)

<a id='section0'></a>
## 1 Introduction

Le **dataset des livres : ventes, évaluations et publication** fournit des informations complètes sur divers aspects des livres.  
Ce dataset permet d’analyser le marché du livre, d’évaluer la performance des auteurs et de découvrir des tendances dans les préférences de lecture.

---

### 1.1 Tableau des colonnes

| Colonne (anglais)        | Colonne (français)       | Description |
|--------------------------|-------------------------|-------------|
| Publishing Year          | Année de publication     | L’année où chaque livre a été publié. Permet d’analyser la répartition chronologique. |
| Book Name                | Nom du livre            | Le titre du livre, unique pour chaque ouvrage. |
| Author                   | Auteur                  | Le(s) nom(s) de l’auteur ou des auteurs. Utile pour analyser leurs contributions et leur réputation. |
| language_code            | Code langue             | Code représentant la langue du livre. Permet des analyses basées sur la langue. |
| Author_Rating            | Note de l’auteur        | Note attribuée à l’auteur basée sur ses œuvres précédentes. |
| Book_average_rating      | Note moyenne du livre   | Moyenne des notes données par les lecteurs pour chaque livre. |
| Book_ratings_count       | Nombre d’évaluations    | Nombre d’évaluations reçues par chaque livre, mesure l’engagement des lecteurs. |
| genre                    | Genre                   | Catégorie littéraire ou genre du livre. Permet d’analyser les tendances par genre. |
| gross sales              | Ventes brutes           | Chiffre d’affaires total généré par le livre. |
| publisher revenue        | Revenus de l’éditeur    | Revenus que l’éditeur tire de la vente de chaque livre. |
| sale price               | Prix de vente           | Prix auquel chaque exemplaire du livre est vendu. |
| sales rank               | Classement des ventes   | Rang du livre selon ses ventes comparé aux autres livres du même genre. |
| units sold               | Unités vendues          | Nombre total d’exemplaires vendus pour chaque titre. |

---

### 1.2 Objectifs du projet EDA

1. **comprendre les donnees**  

2. **Nettoyer les donnees**  

3. **Rechercher des relations**  

4. **Visualiser et faire une analyse statistique**  

5. **Etude de cas**

<a id='section1'></a>
## 2. Imports & Configuration

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

<a id='section2'></a>
## 3. Comprehension du Dataset

In [ ]:
## 3.1 Charger le dataset

In [23]:
df = pd.read_csv("Books_Data_Clean.csv")

In [25]:
## 3.2 Premiere lignes 
df.head()

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

In [35]:
## dimension
print(f"Dimensions : {df.shape[0]} lignes × {df.shape[1]} colonnes")
print(f"  → {df.shape[1]} variables")

Dimensions : 1070 lignes × 15 colonnes
  → 15 variables

In [39]:
## type des donnes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1070 non-null   int64
 1   Publishing Year      1069 non-null   float64
 2   Book Name            1047 non-null   object
 3   Author               1070 non-null   object
 4   language_code        1017 non-null   object
 5   Author_Rating        1070 non-null   object
 6   Book_average_rating  1070 non-null   float64
 7   Book_ratings_count   1070 non-null   int64
 8   genre                1070 non-null   object
 9   gross sales          1070 non-null   float64
 10  publisher revenue    1070 non-null   float64
 11  sale price           1070 non-null   float64
 12  sales rank           1070 non-null   int64
 13  Publisher            1070 non-null   object
 14  units sold           1070 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 125.5+ KB

In [41]:
# Statistiques descriptives
df.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
index,1070.0,534.50,309.03,0.00,267.25,534.50,801.75,1069.00
Publishing Year,1069.0,1971.38,185.08,-560.00,1985.00,2003.00,2010.00,2016.00
Book_average_rating,1070.0,4.01,0.25,2.97,3.85,4.01,4.17,4.77
Book_ratings_count,1070.0,94909.91,31513.24,27308.00,70398.00,89309.00,113906.50,206792.00
gross sales,1070.0,1856.62,3936.92,104.94,372.46,809.74,1487.96,47795.00
publisher revenue,1070.0,843.28,2257.60,0.00,0.00,273.08,721.18,28677.00
sale price,1070.0,4.87,3.56,0.99,1.99,3.99,6.99,33.86
sales rank,1070.0,611.65,369.85,1.00,287.50,595.50,932.50,1273.00
units sold,1070.0,9676.98,15370.57,106.00,551.25,3924.00,5312.25,61560.00

In [43]:
df.columns

Index(['index', 'Publishing Year', 'Book Name', 'Author', 'language_code',
       'Author_Rating', 'Book_average_rating', 'Book_ratings_count', 'genre',
       'gross sales', 'publisher revenue', 'sale price', 'sales rank',
       'Publisher ', 'units sold'],
      dtype='object')

In [61]:
# Valeurs uniques : Variables catégorielles 
for col in ['language_code','Author_Rating', 'genre']:
    print(f"\n '{col}' — {df[col].nunique()} modalités :")
    vc = df[col].value_counts()
    for val, count in vc.items():
        pct = count / len(df) * 100
        print(f"   • {val:<35} : {count:>3} livres ({pct:.1f}%)")

 'language_code' — 8 modalités :
   • eng                                 : 737 livres (68.9%)
   • en-US                               : 234 livres (21.9%)
   • en-GB                               :  30 livres (2.8%)
   • en-CA                               :   7 livres (0.7%)
   • fre                                 :   4 livres (0.4%)
   • spa                                 :   2 livres (0.2%)
   • ara                                 :   2 livres (0.2%)
   • nl                                  :   1 livres (0.1%)

 'Author_Rating' — 4 modalités :
   • Intermediate                        : 625 livres (58.4%)
   • Excellent                           : 362 livres (33.8%)
   • Famous                              :  53 livres (5.0%)
   • Novice                              :  30 livres (2.8%)

 'genre' — 4 modalités :
   • genre fiction                       : 822 livres (76.8%)
   • nonfiction                          : 171 livres (16.0%)
   • fiction                             :  62 livres (5.8%)
   • children                            :  15 livres (1.4%)

<a id='section3'></a>
## 4. Nettoyage des donnees

In [73]:
## Verifier s'il y'a une valeur manquante 
df.isnull().any()

index                  False
Publishing Year         True
Book Name               True
Author                 False
language_code           True
Author_Rating          False
Book_average_rating    False
Book_ratings_count     False
genre                  False
gross sales            False
publisher revenue      False
sale price             False
sales rank             False
Publisher              False
units sold             False
dtype: bool

In [93]:
## visualiser les lignes ayant des valeurs manquantes (Publisher Year , Book name , language code)
df[df[['Publishing Year', 'Book Name', 'language_code']].isnull().any(axis=1)].head(10)

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
22,22,1991.0,Needful Things,Stephen King,NaN,Intermediate,3.87,153821,genre fiction,2772.00,0.000,0.99,23,"Amazon Digital Services, Inc.",2800
24,24,1996.0,NaN,"Kenneth Branagh, William Shakespeare",eng,Intermediate,4.12,156869,genre fiction,2639.34,1583.604,0.99,25,"Amazon Digital Services, Inc.",2666
34,34,2007.0,NaN,Brandon Sanderson,eng,Intermediate,4.35,150736,genre fiction,17980.00,10788.000,8.99,35,Random House LLC,2000
74,74,2007.0,"Are You There, Vodka? It's Me, Chelsea",Chelsea Handler,NaN,Intermediate,3.85,127096,genre fiction,5462.31,3277.386,3.99,76,Hachette Book Group,1369
105,105,2011.0,NaN,Mark Cotta Vaz,eng,Intermediate,4.30,188136,genre fiction,7670.40,4602.240,7.99,108,Penguin Group (USA) LLC,960
109,109,2002.0,Prey,Michael Crichton,NaN,Intermediate,3.72,131352,genre fiction,1850.70,0.000,1.99,114,"Amazon Digital Services, Inc.",930
186,186,2012.0,NaN,Kate Egan,en-US,Famous,4.51,119915,genre fiction,2950.91,1770.546,6.01,205,HarperCollins Publishers,491
190,190,2013.0,NaN,Allie Brosh,eng,Intermediate,4.17,118910,genre fiction,5269.53,3161.718,10.91,210,Penguin Group (USA) LLC,483
207,207,1971.0,Mrs. Frisby and the Rats of NIMH,Robert C. O'Brien,NaN,Intermediate,4.13,135978,genre fiction,1815.45,1089.270,3.99,227,"Amazon Digital Services, Inc.",455
209,209,1953.0,The Little House Collection,"Laura Ingalls Wilder, Garth Williams",NaN,Intermediate,4.33,124320,genre fiction,5195.91,3117.546,11.47,228,Random House LLC,453

In [95]:
## le nombre de valeur manquante pas colonnes
df[['Publishing Year', 'Book Name', 'language_code']].isnull().sum()

Publishing Year     1
Book Name          23
language_code      53
dtype: int64

In [99]:
## Supprimer la ligne où Publishing Year est manquant
df = df.dropna(subset=['Publishing Year'])

## Remplacer les valeurs manquantes de Book Name par "Unknown"
df['Book Name'] = df['Book Name'].fillna('Unknown')

## Remplacer les valeurs manquantes de language_code par "Unknown"
df['language_code'] = df['language_code'].fillna('Unknown')

# Vérification du résultat
df[['Publishing Year', 'Book Name', 'language_code']].isnull().sum()

Publishing Year    0
Book Name          0
language_code      0
dtype: int64

In [105]:
## convertir Publishing Year en entier 
df['Publishing Year'] = df['Publishing Year'].astype('Int64')  # gère les valeurs manquantes
df['Publishing Year'].dtypes

Int64Dtype()

<a id='section3'></a>
## 4. Nettoyage des donnees